// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf5KqNVQT-AMWBR-XXOMo-UwbSYPrD0wU',
    appId: '1:925405520869:web:8513ea79d446866e78050c',
    messagingSenderId: '925405520869',
    projectId: 'memoryapp-a008e',
    authDomain: 'memoryapp-a008e.firebaseapp.com',
    storageBucket: 'memoryapp-a008e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwsOymPb9yeJ1en5NSIWDIfIPYzKUjSmM',
    appId: '1:925405520869:android:c2128798eea7385c78050c',
    messagingSenderId: '925405520869',
    projectId: 'memoryapp-a008e',
    storageBucket: 'memoryapp-a008e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzUm_hzvqCEIq55lMfDEqKypH-hcZx6z8',
    appId: '1:925405520869:ios:85e1c756231c7c0678050c',
    messagingSenderId: '925405520869',
    projectId: 'memoryapp-a008e',
    storageBucket: 'memoryapp-a008e.firebasestorage.app',
    iosBundleId: 'com.example.memoryTaskV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzUm_hzvqCEIq55lMfDEqKypH-hcZx6z8',
    appId: '1:925405520869:ios:85e1c756231c7c0678050c',
    messagingSenderId: '925405520869',
    projectId: 'memoryapp-a008e',
    storageBucket: 'memoryapp-a008e.firebasestorage.app',
    iosBundleId: 'com.example.memoryTaskV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf5KqNVQT-AMWBR-XXOMo-UwbSYPrD0wU',
    appId: '1:925405520869:web:a9856e01bde276d478050c',
    messagingSenderId: '925405520869',
    projectId: 'memoryapp-a008e',
    authDomain: 'memoryapp-a008e.firebaseapp.com',
    storageBucket: 'memoryapp-a008e.firebasestorage.app',
  );
}
